Tying up
tweedegolf/spaeter pull request #9
Opened 2024-01-16 14:57 UTC by diondokter

2024-02-02 13:59 UTC, tdittr requested changes
I think setting the alarm, and reading the capture time from the timer might need another look. Otherwise only some nit-picks.

2024-02-02 13:59 UTC, tdittr commented on firmware/src/adc_capture.rs
>          ahb1: &mut rcc::AHB1,
```suggestion
        apb2: &mut APB2,
        ahb1: &mut AHB1,
```

2024-02-02 13:59 UTC, tdittr commented on firmware/src/adc_capture.rs
> +    ) -> (Self, HertzU32, HertzU32) {
This could get a bit confusing with which HertzU32 belongs to which part.

2024-02-02 13:59 UTC, tdittr commented on firmware/src/adc_capture.rs
> -                _ => panic!("DMA finished wrong buffer!"),
Should we not check if something went wrong? And we actually missed one transfer?

2024-02-02 13:59 UTC, tdittr commented on firmware/src/main.rs
> +        TIM2_OVERFLOWS.fetch_add(1, core::sync::atomic::Ordering::SeqCst);
Isn't this interrupt also called on a capture event? So every time a PTP alarm passed?

2024-02-02 13:59 UTC, tdittr commented on firmware/src/main.rs
> +        let tim2_count = unsafe { (*pac::TIM2::ptr()).cnt.read().cnt().bits() };
I think you wanted to read the capture channel value here. This will give a lightly off reading depending on when the interrupt is called.

2024-02-02 13:59 UTC, tdittr commented on firmware/src/main.rs
> +                *cx.local.ptp_target_time = now + INTERVAL;
There might be a race condition here, if now is almost the new interval. Maybe just always set the alarm to `now+INTERVAL` that way the error does never accumulate.

2024-02-02 13:59 UTC, tdittr commented on signal-detector/src/lib.rs
> +    pub fn feed(&mut self, chunk: &[f32]) -> Vec<SignalPeak, MAX_TRACKED_PEAKS> {
could this then just be a `&[f32; CHUNK_SIZE]`?

2024-02-02 14:04 UTC, diondokter commented on firmware/src/main.rs
> +        TIM2_OVERFLOWS.fetch_add(1, core::sync::atomic::Ordering::SeqCst);
Ah! Didn't know that. Makes sense

2024-02-02 14:04 UTC, diondokter commented on firmware/src/main.rs
> +        let tim2_count = unsafe { (*pac::TIM2::ptr()).cnt.read().cnt().bits() };
Yep, now I understand this timer better. You're right

2024-02-02 14:07 UTC, diondokter commented on firmware/src/adc_capture.rs
> -                _ => panic!("DMA finished wrong buffer!"),
So this check always went wrong for me even though things were working fine.
I think it's because the dma can already jump to the next memory and then this check fails even though that's normal behaviour.

2024-02-02 14:08 UTC, diondokter commented on firmware/src/main.rs
> +                *cx.local.ptp_target_time = now + INTERVAL;
I guess that would be fine too

2024-02-02 14:10 UTC, diondokter commented on signal-detector/src/lib.rs
> +    pub fn feed(&mut self, chunk: &[f32]) -> Vec<SignalPeak, MAX_TRACKED_PEAKS> {
This is all a bit unfortunate. It could yeah, but not without having to create many copies.
With this the `.chunks_exact(CHUNK_SIZE)` function can be used on the big slice we get from the DMA.

If we first need to make it into an array, we'd need to copy everything.
I guess that might be fine, but I have no idea how close to the performance limit we are...

2024-02-02 14:20 UTC, tdittr commented on firmware/src/adc_capture.rs
> -                _ => panic!("DMA finished wrong buffer!"),
Oh, yeah that makes sense, looking at it the check is inverse. If Bank0 is the next one to be finished `current_transfer` should be `memory1` since `memory0` is the one we expect to be finished...

2024-02-02 14:21 UTC, tdittr commented on signal-detector/src/lib.rs
> +    pub fn feed(&mut self, chunk: &[f32]) -> Vec<SignalPeak, MAX_TRACKED_PEAKS> {
Oh, yeah that makes sense, I guess there is no fixed length slice...

2024-02-02 14:23 UTC, tdittr commented on firmware/src/adc_capture.rs
>          ahb1: &mut rcc::AHB1,
Oh, I guess this still needs the `use` statement... gonna fix that on Monday...

2024-02-07 10:30 UTC, tdittr approved these changes
I think this is ready now.

2024-02-13 12:10 UTC, diondokter commented
Ok, let's figure out the frontend in another PR

2024-02-13 12:10 UTC, merged